// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjGSgN-MEr8LhXp5GRDxXzJAcxnN_4O58',
    appId: '1:354155998015:web:1d980d5b048778fe3c818a',
    messagingSenderId: '354155998015',
    projectId: 'canteen-sys',
    authDomain: 'canteen-sys.firebaseapp.com',
    storageBucket: 'canteen-sys.appspot.com',
    measurementId: 'G-YDKN9L6QP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhgS8JpnPFx42pzojT9B_vhxFpkHygNwo',
    appId: '1:354155998015:android:afad55f1ebd146a13c818a',
    messagingSenderId: '354155998015',
    projectId: 'canteen-sys',
    storageBucket: 'canteen-sys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxjyi7OIwc7wTqpofwPeXNwOQ_Cu_mWZg',
    appId: '1:354155998015:ios:0d5022798fd286b93c818a',
    messagingSenderId: '354155998015',
    projectId: 'canteen-sys',
    storageBucket: 'canteen-sys.appspot.com',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxjyi7OIwc7wTqpofwPeXNwOQ_Cu_mWZg',
    appId: '1:354155998015:ios:55646b2ee7a63f933c818a',
    messagingSenderId: '354155998015',
    projectId: 'canteen-sys',
    storageBucket: 'canteen-sys.appspot.com',
    iosBundleId: 'com.example.firebaseConnection.RunnerTests',
  );
}
